export const CREATE_TASK = "CREATE_TASK";

export const SET_TASKS = "SET_TASKS";

export const COMPLETE_TASK = "COMPLETE_TASK";

export const DELETE_TASK = "DELETE_TASK";

export const SEARCH_TASK = "SEARCH_TASK";

export const CHANGE_TASKINPUT_VALUE = "CHANGE_TASKINPUT_VALUE";

export const FILTER_ALL_TASKS = "FILTER_ALL_TASKS";

export const FILTER_DONE_TASKS = "FILTER_DONE_TASKS";

export const FILTER_TODO_TASKS = "FILTER_TODO_TASKS";
